### ISSUE TITLE
Invite please

### ISSUE THREAD

**Issue by MrCaspan** [jschr/trail-status-app#22]
Hey guys we would like to test this out for use with GORBA! Let me know if we can get an invite please. I tried to login with my instagram account and it said I didnt not have a developer role.

**Comment by jschr** [comment]
hey @MrCaspan, I just invited the gorbamtb Instagram account. You should see the invite here under "Tester Invites": https://www.instagram.com/accounts/manage_access/

I haven't touched this app in a long time so I hope things still work. Let me know if you have any questions or issues getting set up.

**Comment by MrCaspan** [comment]
Thanks, I'll talk to the team and see what we can do with it..

question Do you guys use this as your main point everywhere else? like on
the website instead of updating the website you just pull it from this
application.? seems like has a pretty cool API so you can just update it in
one place Instagram and then it propagates everywhere else using webhooks
and APIs.

**Comment by MrCaspan** [comment]
also sorry this is the trail status ig feed

https://www.instagram.com/gltrailsgorba?igsh=cm9kMXlraTJnM3c3

**Comment by jschr** [comment]
No problem, I invited gltrailsgorba. 

Yeah the Hyrdocuts use it on their main website. They just need to make an Instagram post with specific tags and their website updates automatically. 

I volunteered some time to build this for the Hydrocut a number of years ago and some people have built a few things on top of the API. Most recently a couple years ago they added a device at the start of each trail head that shows the current trail status. You can read more about it here: https://www.trailmonitoringsystem.com/

**Comment by MrCaspan** [comment]
oh wow this is awesome!!

**Comment by MrCaspan** [comment]
Is it possible to connect when you have a minute? I dont want to waste your time on here but just curious about how it works exactly and how we could use this service for GORBA trails. My email is {redacted} . Once you email me with your contact info I can remove my email from this post.
